# frozen_string_literal: true

require 'bundler/gem_tasks'
require 'rspec/core/rake_task'
require 'rubocop/rake_task'

RSpec::Core::RakeTask.new(:spec)
RuboCop::RakeTask.new

task default: %i[prepare_build spec rubocop]
task prepare_build: %i[download build:entrypoints]
task package: %i[clobber prepare_build]
